#!/usr/bin/env python3

import os
import subprocess
import sys

# TODO: Warning: imagemagick problem: Exception 325: Premature end of JPEG file
#       example file:
#         /media/vanacker/20158e58-75f5-4c17-bfe9-c9519e811757/memories/2017/05/20170516_175658.jpg  # noqa: #501

if len(sys.argv) > 1:
    filepath = os.path.expanduser(sys.argv[1])
else:
    filepath = os.path.expanduser('~/imagedupes.log')

# read the file generated by imagedupes
with open(filepath) as f:
    lines = f.read().splitlines()

for nr, line in enumerate(lines):
    files = line.split(" ")

    # clean up non-existing files before printing output
    _files = [f for f in files if os.path.isfile(f)]

    for i, f in enumerate(_files):
        sys.stderr.write(f'\rline: {nr}, file: {i}')
        sys.stderr.flush()
        # check for corruption with imagemagick identify
        errors = subprocess.check_output(
            f'identify -verbose {f} 2>&1 > /dev/null',
            shell=True
        )
        if errors:
            print(f)
